branches:
  - "releases/v1"
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: angular
  - - "@semantic-release/release-notes-generator"
    - preset: angular
  - "@semantic-release/github"