branches:
  - name: releases/v+([0-9])
    range: +([0-9])?(.{+([0-9]),x}).x
    channel: +([0-9])?(.{+([0-9]),x}).x
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: angular
  - - "@semantic-release/release-notes-generator"
    - preset: angular
  - "@semantic-release/github"