plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: build
          release: patch
        - type: ci
          release: patch
        - type: docs
          release: patch
        - type: fix
          release: patch
        - type: test
          release: patch
        - type: feat
          release: minor
        - type: perf
          release: minor
        - type: refactor
          release: minor
        - type: upgrade
          release: major
        - type: break
          release: major
        - scope: no-release
          release: false
  - - "@semantic-release/release-notes-generator"
    - preset: angular
  - "@semantic-release/github"
